### ISSUE TITLE
New Release / Version NPM

### ISSUE THREAD

**Issue by JanLoebel** [arg20/circle-to-radius#26]
Hi, 

I would need a new release of the current version of circle-to-polygon. You've merged my pull request but I would need it available via npm.

Could you please make a new release please?! :)

Best regards,
Jan

**Comment by gabzim** [comment]
Hi @JanLoebel, we published 2.0.2 with the latest changes in master. Let me know if there's something wrong with th release

**Comment by JanLoebel** [comment]
Thanks looks great :)
