### ISSUE TITLE
ES6 syntax breaks uglify()

### ISSUE THREAD

**Issue by doug-numetric** [arg20/circle-to-radius#3]
The use of ES6 syntax `let`
here:
https://github.com/arg20/circle-to-radius/blob/master/index.js#L27
and here:
https://github.com/arg20/circle-to-radius/blob/master/index.js#L32

breaks uglify.  You are careful to use var and ES5 syntax throughout the rest of the file.  I suspect this was an oversight.

**Comment by doug-numetric** [comment]
Looks like you have a Pull request to fix this.

**Comment by gabzim** [comment]
Merged! thanks for the heads up.

**Comment by gabzim** [comment]
Published to npm as v1.0.2
