### ISSUE TITLE
Oval Polygon

### ISSUE THREAD

**Issue by arzanardi** [arg20/circle-to-radius#34]
Hello, I put the polygon returned by the function on a map but at the end I got an oval shape
Where can I be wrong? 

See: 
<img src="https://i.ibb.co/z2dpBpS/oval.png">

**Comment by arzanardi** [comment]
I believer that the return in 
https://github.com/gabzim/circle-to-polygon/blob/9874599953bd910ca61cc4a0556cea74be0e5901/index.js#L27

Shold be `return [toDegrees(lon), toDegrees(lat)];`

**Comment by gabzim** [comment]
Hi @arzanardi can you give me a code example to reproduce? (coords, edges, etc)

**Comment by johachi** [comment]
Hi @arzanardi !

Your image link seems to be broken. Could you please re-upload the image (you can upload images directly to the github comments. We also (as @gabzim said) need to know what coordinates you used together with the other parameters you sent.

**Comment by arzanardi** [comment]
Hi guys,
You can ignore the case, I had inverted lat and lon.

Thank you so much for your attention.

**Comment by gabzim** [comment]
Excellent @arzanardi, good to know that inverting them can cause the issue. I'll keep that in mind if this comes back again.

**Comment by chramos** [comment]
I agree guys, the library is amazing and really helpful, but the api is a bit confusing.
I spent lots of time to understand why I was getting oval Polygon

**Comment by johachi** [comment]
> I agree guys, the library is amazing and really helpful, but the api is a bit confusing.
I spent lots of time to understand why I was getting oval Polygon

Thank you for the feedback! Any suggestion on how we could make the documentation clearer?
