### ISSUE TITLE
Drawing a semi circle

### ISSUE THREAD

**Issue by mosi6** [arg20/circle-to-radius#50]
Hi! 
I need to be able to convert semi circles and quarter circles to geojson. I wonder if there’s any way to modify this script easily to accommodate for that.
Thanks

**Comment by johachi** [comment]
It's actually relatively easy to do, just change 

https://github.com/gabzim/circle-to-polygon/blob/d23c0ad86091be60c6f733ab43f2599c04393285/index.js#L41

to

```js
 for (var i = 0; i <= n; ++i) {
```

and

https://github.com/gabzim/circle-to-polygon/blob/d23c0ad86091be60c6f733ab43f2599c04393285/index.js#L43-L45

to 

```js

 offset( 
   center, radius, earthRadius, start + (direction * Math.PI * -i) / n
 )
```

I have already tested and verified that this works.

Please let me know if you have any more questions or I will close this issue 🙂

**Comment by mosi6** [comment]
This code only lets me draw semi circles(180 deg) specifically and I want a generic way to draw any angle(quarter circles and any other angle). I already kind of implemented it on my own but I did use the math from this project so thanks a lot for that.
